//! `exfer-walletd init` — one-shot deployment scaffolder.
//!
//! Goal: take a fresh host from "binary downloaded" to "daemon ready
//! to start" without copying anything out of the docs. The command
//! generates two fresh random tokens, writes an env file with mode
//! 0600, and creates the wallet directory with mode 0700.
//!
//! Idempotent by default: a pre-existing env file is left alone so re-
//! running init can't silently rotate tokens that are already in use.
//! `--force` overrides.

use std::fs::{DirBuilder, OpenOptions};
use std::io::Write;
use std::net::SocketAddr;
use std::path::{Path, PathBuf};

use clap::Args;
use rand::{rngs::OsRng, RngCore};

#[derive(Args, Debug)]
pub struct InitArgs {
    /// Where to write the env file.
    #[arg(long, default_value = "/etc/exfer-walletd/env")]
    pub env_file: PathBuf,

    /// Wallet directory to create.
    #[arg(long, default_value = "/var/lib/exfer-walletd")]
    pub wallet_dir: PathBuf,

    /// Bind address recorded in the env file.
    #[arg(long, default_value = "127.0.0.1:8080")]
    pub bind: SocketAddr,

    /// Upstream Exfer node JSON-RPC URL (or comma-separated list)
    /// recorded in the env file. Edit afterwards to point at your node
    /// if you don't run one on loopback.
    #[arg(long, default_value = "http://127.0.0.1:9334")]
    pub node_rpc: String,

    /// Print the rendered env file to stdout instead of writing to
    /// disk. Useful when secrets live in a vault and you don't want a
    /// file on the host.
    #[arg(long)]
    pub print: bool,

    /// Overwrite an existing env file. Off by default so re-running
    /// `init` can't accidentally rotate tokens that are in use.
    #[arg(long)]
    pub force: bool,
}

pub fn run(args: InitArgs) -> anyhow::Result<()> {
    let read_token = random_hex_token();
    let spend_token = random_hex_token();

    let env_body = render_env(&args, &read_token, &spend_token);

    if args.print {
        print!("{env_body}");
        return Ok(());
    }

    create_dir(&args.wallet_dir, 0o700)?;
    if let Some(parent) = args.env_file.parent() {
        create_dir(parent, 0o750)?;
    }
    write_env_file(&args.env_file, &env_body, args.force)?;

    eprintln!();
    eprintln!("  wrote    {}", args.env_file.display());
    eprintln!("  created  {}", args.wallet_dir.display());
    eprintln!();
    eprintln!("Tokens (also stored in the env file):");
    eprintln!("  READ   {read_token}");
    eprintln!("  SPEND  {spend_token}");
    eprintln!();
    eprintln!("Next steps:");
    eprintln!("  1. If your Exfer node isn't on loopback, edit");
    eprintln!("     {} and set EXFER_NODE_RPC.", args.env_file.display());
    eprintln!("  2. Install the systemd unit:");
    eprintln!("     sudo curl -L -o /etc/systemd/system/exfer-walletd.service \\");
    eprintln!("       https://raw.githubusercontent.com/exfer-stack/exfer-walletd/main/deploy/systemd/exfer-walletd.service");
    eprintln!("  3. Create the runtime user (if you don't have one):");
    eprintln!("     sudo useradd --system --home {} --shell /usr/sbin/nologin exfer-walletd",
        args.wallet_dir.display());
    eprintln!("     sudo chown -R exfer-walletd:exfer-walletd {}", args.wallet_dir.display());
    eprintln!("     sudo chown root:exfer-walletd {}", args.env_file.display());
    eprintln!("     sudo chmod 0640 {}", args.env_file.display());
    eprintln!("  4. Start:");
    eprintln!("     sudo systemctl daemon-reload");
    eprintln!("     sudo systemctl enable --now exfer-walletd");
    eprintln!();

    Ok(())
}

fn random_hex_token() -> String {
    let mut bytes = [0u8; 32];
    OsRng.fill_bytes(&mut bytes);
    hex::encode(bytes)
}

fn render_env(args: &InitArgs, read: &str, spend: &str) -> String {
    format!(
        "# Generated by `exfer-walletd init`.\n\
         # Mode 0600 — do not commit, do not share.\n\
         \n\
         # --- Auth -------------------------------------------------\n\
         WALLETD_AUTH_TOKEN_READ={read}\n\
         WALLETD_AUTH_TOKEN_SPEND={spend}\n\
         \n\
         # --- Networking -------------------------------------------\n\
         # Loopback bind is the safe default — put Caddy/nginx in front\n\
         # for TLS. Public binds (0.0.0.0, public IP) require also\n\
         # setting WALLETD_ALLOW_PUBLIC_BIND=1 to acknowledge that a\n\
         # TLS terminator sits in front of walletd.\n\
         WALLETD_BIND={bind}\n\
         EXFER_NODE_RPC={node_rpc}\n\
         \n\
         # --- Storage ----------------------------------------------\n\
         WALLETD_WALLET_DIR={wallet_dir}\n\
         \n\
         # --- Misc -------------------------------------------------\n\
         RUST_LOG=info,exfer_walletd=info\n\
         WALLETD_UPSTREAM_TIMEOUT_SECS=30\n\
        ",
        bind = args.bind,
        node_rpc = args.node_rpc,
        wallet_dir = args.wallet_dir.display(),
    )
}

fn create_dir(path: &Path, mode: u32) -> anyhow::Result<()> {
    if path.exists() {
        return Ok(());
    }
    let mut b = DirBuilder::new();
    b.recursive(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::DirBuilderExt;
        b.mode(mode);
    }
    #[cfg(not(unix))]
    let _ = mode;
    b.create(path)?;
    Ok(())
}

fn write_env_file(path: &Path, body: &str, force: bool) -> anyhow::Result<()> {
    let mut opts = OpenOptions::new();
    opts.write(true).truncate(true);
    if force {
        opts.create(true);
    } else {
        opts.create_new(true);
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        opts.mode(0o600);
    }

    let mut f = opts.open(path).map_err(|e| {
        if e.kind() == std::io::ErrorKind::AlreadyExists {
            anyhow::anyhow!(
                "{} already exists; refusing to overwrite. Pass --force if you really want to regenerate tokens (any client currently using the old tokens will start getting 401s).",
                path.display()
            )
        } else {
            anyhow::Error::from(e)
        }
    })?;
    f.write_all(body.as_bytes())?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn random_token_is_64_hex_chars() {
        let t = random_hex_token();
        assert_eq!(t.len(), 64);
        assert!(t.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn two_calls_produce_distinct_tokens() {
        // OsRng is a CSPRNG; collision in 32 random bytes is fantasy.
        assert_ne!(random_hex_token(), random_hex_token());
    }

    #[test]
    fn render_env_includes_both_tokens_and_paths() {
        let args = InitArgs {
            env_file: PathBuf::from("/x/env"),
            wallet_dir: PathBuf::from("/y/wallets"),
            bind: "127.0.0.1:8080".parse().unwrap(),
            node_rpc: "http://node:9334".into(),
            print: true,
            force: false,
        };
        let body = render_env(&args, "AAAA", "BBBB");
        assert!(body.contains("WALLETD_AUTH_TOKEN_READ=AAAA"));
        assert!(body.contains("WALLETD_AUTH_TOKEN_SPEND=BBBB"));
        assert!(body.contains("WALLETD_BIND=127.0.0.1:8080"));
        assert!(body.contains("EXFER_NODE_RPC=http://node:9334"));
        assert!(body.contains("WALLETD_WALLET_DIR=/y/wallets"));
    }

    #[test]
    fn write_then_refuse_to_clobber() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("env");
        write_env_file(&path, "first=1\n", false).unwrap();
        let err = write_env_file(&path, "second=2\n", false).unwrap_err();
        assert!(err.to_string().contains("refusing to overwrite"));
        // Force should succeed.
        write_env_file(&path, "third=3\n", true).unwrap();
        let s = std::fs::read_to_string(&path).unwrap();
        assert_eq!(s, "third=3\n");
    }
}
